name: ywy
age: 15
date: 2005/1/1

#student:
#  name: ywy
#  age: 15

map:
  k1: v1
  k2: v2

student2: { name: ywy, age: 15 }

list:
  - yan
  - wei
  - yi

students:
  - name: jack
    age: 21
  - name: mack
    age: 15
  - { name: duck, age: 22 }

server:
  port: ${myPort:88}

myPort: 80

student:
  lastName: ywy
  age: 30
  boss: true
  birthday: 2005/1/1
  maps:
    name: jack
    age: 11
  maps2: { name: duck, age: 12 }
  list:
    - name: 小白
      age: 3
    - { name: 小黄, age: 5 }
  dog:
    name: 小黑
    age: 1
  arr:
    - a
    - b
    - c
  arr2: [d, e, f]
  dogMap:
    xb: { name: 小布, age: 9 }
    xh:
      name: 小红
      age: 6

# SpringBoot整合MyBaits相关配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-study?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml # mapper映射文件路径
  type-aliases-package: com.springboot.domain   # 配置哪个包下的类有默认的别名
