server:
  port: 80

# SpringBoot整合MyBaits相关配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-study?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  aop:
    proxy-target-class: false
  redis:
    host: 127.0.0.1 # IP
    port: 6379 # 端口
  profiles:
    active: test
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml # mapper映射文件路径
  type-aliases-package: com.springboot.domain   # 配置哪个包下的类有默认的别名